# Generated by Django 6.0.8 on 2026-09-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name="Chat ID"),
        ),
    ]
