# Generated by Django 6.0.8 on 2026-09-01 16:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=200, verbose_name="Название")),
                ("address", models.CharField(blank=True, max_length=500, null=True, verbose_name="Адрес")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=150, verbose_name="Действие")),
                ("pleasant_habit", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "ежедневная"),
                            ("two_days", "2 дня"),
                            ("three_days", "3 дня"),
                            ("four_days", "4 дня"),
                            ("five_days", "5 дней"),
                            ("six_days", "6 дней"),
                            ("weekly", "еженедельно"),
                        ],
                        default="daily",
                        max_length=12,
                        verbose_name="Периодичность",
                    ),
                ),
                (
                    "remuneration",
                    models.CharField(blank=True, max_length=250, null=True, verbose_name="Вознаграждение"),
                ),
                (
                    "completion_time",
                    models.PositiveSmallIntegerField(
                        validators=[django.core.validators.MaxValueValidator(120)], verbose_name="Время на выполнение"
                    ),
                ),
                ("publicity", models.BooleanField(default=False, verbose_name="Признак публичности")),
                (
                    "connection_habit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habit.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habit.location",
                        verbose_name="Место выполнения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("-time",),
            },
        ),
    ]
